# Generated by Django 4.0.5 on 2022-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeds',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seeds'),
        ),
    ]
